version: "3.1"
services:
  webserver:
    image: nginx:alpine
    container_name: app-webserver
    working_dir: /application
    volumes:
      - ../src:/application
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
  php-fpm:
    build: php-fpm
    container_name: app-php-fpm
    working_dir: /application
    volumes:
      - ../src:/application
      - ./php-fpm/php-ini-overrides.ini:/etc/php/7.3/fpm/conf.d/99-overrides.ini
